// sim/registry.js — the item registry: every thing the player can hold, craft,
// or place, in one data-driven table. kind drives how it behaves:
//   resource     raw / decomposed material
//   intermediate crafted part feeding deeper recipes
//   tool         equippable, changes the right-click verb
//   buildable    placeable structure (machine / wall / belt / ...)

export const KIND = { RESOURCE: "resource", INTERMEDIATE: "intermediate", TOOL: "tool", BUILDABLE: "buildable", TRINKET: "trinket" };

export const ITEMS = {
  // ---- raw / decomposed resources ----
  wood:          { name: "Wood", kind: KIND.RESOURCE, stack: 200, color: "#6e4d2c" },
  fabric:        { name: "Fabric", kind: KIND.RESOURCE, stack: 200, color: "#7a5a5a" },
  scrap:         { name: "Metal scrap", kind: KIND.RESOURCE, stack: 200, color: "#8a8a92" },
  concrete:      { name: "Concrete", kind: KIND.RESOURCE, stack: 200, color: "#6f6d66" },
  carpet:        { name: "Carpet strip", kind: KIND.RESOURCE, stack: 200, color: "#b6ad5e" },
  string:        { name: "String", kind: KIND.RESOURCE, stack: 200, color: "#d8d2bd" },
  fuel:          { name: "Fuel", kind: KIND.RESOURCE, stack: 200, color: "#caa23a" },
  fiber:         { name: "Fiber", kind: KIND.RESOURCE, stack: 200, color: "#7a8a4a" },
  electronics:   { name: "Electronics", kind: KIND.RESOURCE, stack: 200, color: "#3a5a7a" },
  wiring:        { name: "Wiring", kind: KIND.RESOURCE, stack: 200, color: "#b07a3a" },
  plastic:       { name: "Plastic", kind: KIND.RESOURCE, stack: 200, color: "#cfd6da" },
  food:          { name: "Food", kind: KIND.RESOURCE, stack: 200, color: "#9a6a3a" },
  almond_water:  { name: "Almond water", kind: KIND.RESOURCE, stack: 200, color: "#8fb6a4" },
  heartwood:     { name: "Heartwood", kind: KIND.RESOURCE, stack: 200, color: "#3a8a45" },
  electrum:      { name: "Raw electrum", kind: KIND.RESOURCE, stack: 200, color: "#d9c25a" },
  stygium:       { name: "Stygium ore", kind: KIND.RESOURCE, stack: 200, color: "#7c8190" },
  unobtanium:    { name: "Unobtanium", kind: KIND.RESOURCE, stack: 200, color: "#a45ff0" },

  // ---- minerals (mined; each carries a property — see depth-design.md) ----
  basalt:        { name: "Basalt", kind: KIND.RESOURCE, stack: 200, color: "#3a3a40", prop: "insulative" },
  quartz:        { name: "Quartz", kind: KIND.RESOURCE, stack: 200, color: "#d8d2e0", prop: "refractive" },
  cobalt:        { name: "Cobalt", kind: KIND.RESOURCE, stack: 200, color: "#3a5aa0", prop: "magnetic" },
  brimstone:     { name: "Brimstone", kind: KIND.RESOURCE, stack: 200, color: "#b6a23a", prop: "reactive" },
  galena:        { name: "Galena", kind: KIND.RESOURCE, stack: 200, color: "#5a5a66", prop: "dense" },
  quicksilver:   { name: "Quicksilver", kind: KIND.RESOURCE, stack: 100, color: "#c0c4cc", prop: "liquid-conductive" },
  niter:         { name: "Niter", kind: KIND.RESOURCE, stack: 200, color: "#e6e0c0", prop: "oxidizer" },

  // ---- organics (farmed / decomposed) ----
  silk:          { name: "Raw silk", kind: KIND.RESOURCE, stack: 200, color: "#e8e2cf" },
  spores:        { name: "Spores", kind: KIND.RESOURCE, stack: 200, color: "#7ad0a0" },
  leather:       { name: "Leather", kind: KIND.RESOURCE, stack: 200, color: "#8a5a3a" },
  bone:          { name: "Bone", kind: KIND.RESOURCE, stack: 200, color: "#ddd6c0" },
  seeds:         { name: "Seeds", kind: KIND.RESOURCE, stack: 200, color: "#9a8a4a" },
  grain:         { name: "Grain", kind: KIND.RESOURCE, stack: 200, color: "#c2a85a" },
  meat:          { name: "Meat", kind: KIND.RESOURCE, stack: 200, color: "#a4503a" },
  egg:           { name: "Egg", kind: KIND.RESOURCE, stack: 200, color: "#efe6d0" },
  milk:          { name: "Milk", kind: KIND.RESOURCE, stack: 200, color: "#f0f0e8" },

  // ---- intermediates ----
  plank:         { name: "Plank", kind: KIND.INTERMEDIATE, stack: 200, color: "#8a6536" },
  electrum_ingot:{ name: "Electrum ingot", kind: KIND.INTERMEDIATE, stack: 200, color: "#e0cf6a" },
  electrum_plate:{ name: "Electrum plate", kind: KIND.INTERMEDIATE, stack: 200, color: "#cabf66" },
  wire:          { name: "Wire", kind: KIND.INTERMEDIATE, stack: 200, color: "#b07a3a" },
  concrete_block:{ name: "Concrete block", kind: KIND.INTERMEDIATE, stack: 200, color: "#7a7870" },
  wooden_gear:   { name: "Wooden gear", kind: KIND.INTERMEDIATE, stack: 200, color: "#7a5a30" },
  machine_frame: { name: "Machine frame", kind: KIND.INTERMEDIATE, stack: 100, color: "#9a8a5a" },
  stygian_powder:{ name: "Stygian powder", kind: KIND.INTERMEDIATE, stack: 200, color: "#4a4658" },

  // ---- mid era: stygian iron chain (industrial) ----
  stygian_iron:  { name: "Stygian iron", kind: KIND.INTERMEDIATE, stack: 200, color: "#6a5f86" },
  stygian_plate: { name: "Stygian plate", kind: KIND.INTERMEDIATE, stack: 200, color: "#7a6f96" },
  stygian_gear:  { name: "Stygian gear", kind: KIND.INTERMEDIATE, stack: 200, color: "#5a5276" },
  circuit_board: { name: "Circuit board", kind: KIND.INTERMEDIATE, stack: 200, color: "#2f6a4a" },
  advanced_frame:{ name: "Advanced frame", kind: KIND.INTERMEDIATE, stack: 100, color: "#8a7faa" },
  ammo:          { name: "Ammo", kind: KIND.INTERMEDIATE, stack: 200, color: "#b8945a" },
  electrum_dust: { name: "Electrum dust", kind: KIND.INTERMEDIATE, stack: 200, color: "#c9b86a" },
  // alchemy / processed minerals
  black_sulfur:  { name: "Black sulfur", kind: KIND.INTERMEDIATE, stack: 200, color: "#2a2630", prop: "combustive" },
  acid:          { name: "Acid", kind: KIND.INTERMEDIATE, stack: 100, color: "#9ad24a", prop: "reactive" },
  magnetiron:    { name: "Magnetiron", kind: KIND.INTERMEDIATE, stack: 200, color: "#4a4a6a", prop: "magnetic" },
  stygian_steel: { name: "Stygian steel", kind: KIND.INTERMEDIATE, stack: 200, color: "#54506a" },
  pigment:       { name: "Pigment", kind: KIND.INTERMEDIATE, stack: 200, color: "#c05a8a" },
  tonic:         { name: "Tonic", kind: KIND.INTERMEDIATE, stack: 50, color: "#5ad0b0" },
  amalgam:       { name: "Amalgam", kind: KIND.INTERMEDIATE, stack: 100, color: "#aab0bc" },
  // machine modules — slot into a machine to specialize it
  speed_module:  { name: "Speed module", kind: KIND.INTERMEDIATE, stack: 50, color: "#d86a6a", module: { speed: 0.5 } },
  efficiency_module: { name: "Efficiency module", kind: KIND.INTERMEDIATE, stack: 50, color: "#6ad88a", module: { eff: 0.3 } },
  productivity_module: { name: "Productivity module", kind: KIND.INTERMEDIATE, stack: 50, color: "#c06ad8", module: { prod: 0.25 } },
  // kiln / mill products
  glass:         { name: "Glass", kind: KIND.INTERMEDIATE, stack: 200, color: "#bfe0e6" },
  brick:         { name: "Brick", kind: KIND.INTERMEDIATE, stack: 200, color: "#9a5a44" },
  charcoal:      { name: "Charcoal", kind: KIND.INTERMEDIATE, stack: 200, color: "#2c2c2c", prop: "fuel" },
  gravel:        { name: "Gravel", kind: KIND.INTERMEDIATE, stack: 200, color: "#7a7870" },
  sand:          { name: "Sand", kind: KIND.INTERMEDIATE, stack: 200, color: "#d8c890" },
  lens:          { name: "Lens", kind: KIND.INTERMEDIATE, stack: 200, color: "#cfeaf0" },
  motor:         { name: "Motor", kind: KIND.INTERMEDIATE, stack: 100, color: "#5a5a72" },
  foldglass:     { name: "Foldglass", kind: KIND.INTERMEDIATE, stack: 100, color: "#b0e0d8", prop: "volatile" },
  basalt_block:  { name: "Basalt block", kind: KIND.INTERMEDIATE, stack: 200, color: "#34343a" },
  superconductor:{ name: "Superconductor", kind: KIND.INTERMEDIATE, stack: 100, color: "#9ad8ff", prop: "superconductive" },
  // schematics (found loot) — picking one up unlocks its alternate recipe
  schem_cast_plate:    { name: "Schematic: cast plate", kind: KIND.RESOURCE, stack: 20, color: "#cfe0a0", schematic: true },
  schem_fast_wire:     { name: "Schematic: wire die", kind: KIND.RESOURCE, stack: 20, color: "#cfe0a0", schematic: true },
  schem_drum_mag:      { name: "Schematic: drum mag", kind: KIND.RESOURCE, stack: 20, color: "#cfe0a0", schematic: true },
  schem_superconductor:{ name: "Schematic: superconductor", kind: KIND.RESOURCE, stack: 20, color: "#cfe0a0", schematic: true },
  // textiles & food
  silk_thread:   { name: "Silk thread", kind: KIND.INTERMEDIATE, stack: 200, color: "#efe9d8" },
  silk_cloth:    { name: "Silk cloth", kind: KIND.INTERMEDIATE, stack: 200, color: "#f2eddf" },
  rope:          { name: "Rope", kind: KIND.INTERMEDIATE, stack: 200, color: "#b8a878" },
  compost:       { name: "Compost", kind: KIND.INTERMEDIATE, stack: 200, color: "#5a4a30" },
  flour:         { name: "Flour", kind: KIND.INTERMEDIATE, stack: 200, color: "#e6dcc0" },
  dough:         { name: "Dough", kind: KIND.INTERMEDIATE, stack: 200, color: "#d8c89a" },
  bread:         { name: "Bread", kind: KIND.INTERMEDIATE, stack: 200, color: "#b88a4a" },
  // found objects (scavenged — usable and/or dismantle into the above)
  adhesive:      { name: "Adhesive", kind: KIND.RESOURCE, stack: 200, color: "#ccc0a0" },
  battery:       { name: "Battery", kind: KIND.RESOURCE, stack: 100, color: "#3a8a5a" },
  keys:          { name: "Keys", kind: KIND.RESOURCE, stack: 100, color: "#d8c060" },
  flashlight:    { name: "Flashlight", kind: KIND.BUILDABLE, stack: 5, w: 1, h: 1, color: "#d8d060", light: 5 },

  // ---- tools (equippable) ----
  wooden_pick:   { name: "Wooden pickaxe", kind: KIND.TOOL, stack: 1 },
  axe:           { name: "Axe", kind: KIND.TOOL, stack: 1 },
  crowbar:       { name: "Crowbar", kind: KIND.TOOL, stack: 1 },
  electrum_pick: { name: "Electrum pickaxe", kind: KIND.TOOL, stack: 1 },
  electrum_axe:  { name: "Electrum axe", kind: KIND.TOOL, stack: 1 },
  electrum_blade:{ name: "Electrum blade", kind: KIND.TOOL, stack: 1 },
  musket:        { name: "Musket", kind: KIND.TOOL, stack: 1 },
  // mid-era stygian tools + the rifle
  stygian_pick:  { name: "Stygian pickaxe", kind: KIND.TOOL, stack: 1 },
  stygian_axe:   { name: "Stygian axe", kind: KIND.TOOL, stack: 1 },
  stygian_blade: { name: "Stygian blade", kind: KIND.TOOL, stack: 1 },
  rifle:         { name: "Rifle", kind: KIND.TOOL, stack: 1 },
  fire_axe:      { name: "Fire axe", kind: KIND.TOOL, stack: 1 }, // found, not crafted

  // ---- buildables ----
  // `draw` = power units consumed when running; `supply` = power produced.
  workbench:     { name: "Workbench", kind: KIND.BUILDABLE, stack: 50, w: 2, h: 1, color: "#6b4a2b" },
  concrete_forge:{ name: "Concrete forge", kind: KIND.BUILDABLE, stack: 50, w: 2, h: 2, color: "#5a5550", machine: "forge" },
  crusher:       { name: "Crusher", kind: KIND.BUILDABLE, stack: 50, w: 2, h: 2, color: "#54545a", machine: "crusher", draw: 4 },
  assembler:     { name: "Assembler", kind: KIND.BUILDABLE, stack: 50, w: 2, h: 2, color: "#4a5a6a", machine: "assembler", draw: 5 },
  wood_generator:{ name: "Wood generator", kind: KIND.BUILDABLE, stack: 50, w: 2, h: 2, color: "#6e4d2c", machine: "generator", supply: 10, burns: "fuel" },
  // mid-era industrial machines (grid-powered)
  stygian_forge: { name: "Stygian forge", kind: KIND.BUILDABLE, stack: 50, w: 2, h: 2, color: "#4a4458", machine: "styforge", draw: 6 },
  stygian_assembler: { name: "Stygian assembler", kind: KIND.BUILDABLE, stack: 50, w: 2, h: 2, color: "#3f4a5a", machine: "styassembler", draw: 8 },
  powder_generator: { name: "Powder generator", kind: KIND.BUILDABLE, stack: 50, w: 2, h: 2, color: "#54506a", machine: "generator", supply: 35, burns: "stygian_powder" },
  turret:        { name: "Auto-turret", kind: KIND.BUILDABLE, stack: 30, w: 1, h: 1, color: "#5a5266", machine: "turret", draw: 3 },
  stygian_wall:  { name: "Stygian wall", kind: KIND.BUILDABLE, stack: 100, w: 1, h: 1, color: "#5a5470" },
  basalt_wall:   { name: "Basalt wall", kind: KIND.BUILDABLE, stack: 100, w: 1, h: 1, color: "#2e2e34" },
  window:        { name: "Window", kind: KIND.BUILDABLE, stack: 100, w: 1, h: 1, color: "#bfe0e6" },
  // recipe-select factories (combine inputs; show the chosen recipe)
  cauldron:      { name: "Alchemy cauldron", kind: KIND.BUILDABLE, stack: 30, w: 2, h: 2, color: "#3a3030", machine: "cauldron", draw: 4 },
  crucible:      { name: "Metal crucible", kind: KIND.BUILDABLE, stack: 30, w: 2, h: 2, color: "#5a3a2a", machine: "crucible", draw: 6 },
  loom:          { name: "Loom", kind: KIND.BUILDABLE, stack: 30, w: 2, h: 2, color: "#7a6a4a", machine: "loom", draw: 2 },
  stygian_belt:  { name: "Stygian belt", kind: KIND.BUILDABLE, stack: 200, w: 1, h: 1, color: "#46465a", logi: "belt", speed: 3.0 },
  stygian_arm:   { name: "Stygian arm", kind: KIND.BUILDABLE, stack: 100, w: 1, h: 1, color: "#5a4a6a", logi: "arm", draw: 2, fast: true },
  chest:         { name: "Chest", kind: KIND.BUILDABLE, stack: 50, w: 1, h: 1, color: "#7a5a36", machine: "chest" },
  crate:         { name: "Crate", kind: KIND.BUILDABLE, stack: 50, w: 1, h: 1, color: "#6a4a2a", machine: "chest" },

  // logistics — belts/arms are walkable (not solid)
  belt:          { name: "Belt", kind: KIND.BUILDABLE, stack: 200, w: 1, h: 1, color: "#3a3a40", logi: "belt" },
  arm:           { name: "Automator arm", kind: KIND.BUILDABLE, stack: 100, w: 1, h: 1, color: "#5a4a3a", logi: "arm", draw: 1 },

  // belt-mounted processors — sit ON a belt, transform whatever passes (not recipe-specific)
  smelter:       { name: "Smelter", kind: KIND.BUILDABLE, stack: 50, w: 1, h: 1, color: "#7a4a3a", process: "smelt", beltMount: true, draw: 3, rate: 1.2 },
  presser:       { name: "Presser", kind: KIND.BUILDABLE, stack: 50, w: 1, h: 1, color: "#5a5a64", process: "press", beltMount: true, draw: 3, rate: 1.0 },
  mill:          { name: "Mill", kind: KIND.BUILDABLE, stack: 50, w: 1, h: 1, color: "#6a6a72", process: "crush", beltMount: true, draw: 3, rate: 1.0 },
  washer:        { name: "Washer", kind: KIND.BUILDABLE, stack: 50, w: 1, h: 1, color: "#4a6a7a", process: "wash", beltMount: true, draw: 2, rate: 1.0 },

  concrete_wall: { name: "Concrete wall", kind: KIND.BUILDABLE, stack: 100, w: 1, h: 1, color: "#7a7870" },
  wooden_door:   { name: "Wooden door", kind: KIND.BUILDABLE, stack: 50, w: 1, h: 1, color: "#8a6536" },
  power_pole:    { name: "Power pole", kind: KIND.BUILDABLE, stack: 50, w: 1, h: 1, color: "#7a6a4a" },
  torch:         { name: "Torch", kind: KIND.BUILDABLE, stack: 50, w: 1, h: 1, color: "#caa23a", light: 4 },
  lantern:       { name: "Lantern", kind: KIND.BUILDABLE, stack: 20, w: 1, h: 1, color: "#e0b24a", light: 6 },
  bedroll:       { name: "Bedroll", kind: KIND.BUILDABLE, stack: 5, w: 1, h: 2, color: "#7a5a5a" },
  tinker_bench:  { name: "Tinker bench", kind: KIND.BUILDABLE, stack: 20, w: 2, h: 1, color: "#6a5a7a" },
  // base-building cozy layer (apply to built walls / floors — placement-special)
  wallpaper:     { name: "Wallpaper", kind: KIND.BUILDABLE, stack: 200, w: 1, h: 1, color: "#c9b86a", surface: "wall" },
  floor_tile:    { name: "Floor tiling", kind: KIND.BUILDABLE, stack: 200, w: 1, h: 1, color: "#9aa0a6", surface: "floor" },
  animal_pen:    { name: "Animal pen", kind: KIND.BUILDABLE, stack: 20, w: 2, h: 2, color: "#7a6a44", machine: "pen" },

  // ---- weapons / ammo as items (modular + thrown + bow) ----
  bow:           { name: "Bow", kind: KIND.TOOL, stack: 1, ranged: true, bow: true },
  crossbow:      { name: "Crossbow", kind: KIND.TOOL, stack: 1, ranged: true, bow: true },
  bladed_yoyo:   { name: "Bladed yo-yo", kind: KIND.TOOL, stack: 1 },
  arrow:         { name: "Arrow", kind: KIND.INTERMEDIATE, stack: 200, color: "#b8a878" },
  grenade:       { name: "Grenade", kind: KIND.INTERMEDIATE, stack: 50, color: "#5a6a4a" },
  molotov:       { name: "Molotov", kind: KIND.INTERMEDIATE, stack: 50, color: "#b8643a" },
  lead_ball:     { name: "Lead ball", kind: KIND.INTERMEDIATE, stack: 200, color: "#5a5a66" },

  // ===== TRINKETS & ARMOR (equip in a slot for an EFFECT; no durability) =====
  // slot: head|goggles|neck|chest|legs|shoes|back|gloves|free
  // armor (head/chest/legs/shoes)
  hard_hat:      { name: "Hard hat", kind: KIND.TRINKET, slot: "head", stack: 1, color: "#d8c000", effect: { defense: 2 } },
  riot_helm:     { name: "Riot helm", kind: KIND.TRINKET, slot: "head", stack: 1, color: "#3a4654", effect: { defense: 5 } },
  kevlar_vest:   { name: "Kevlar vest", kind: KIND.TRINKET, slot: "chest", stack: 1, color: "#3a3f34", effect: { defense: 6 } },
  galena_plate_armor: { name: "Galena plate", kind: KIND.TRINKET, slot: "chest", stack: 1, color: "#5a5a66", effect: { defense: 12, move: -0.12 } },
  featherweave:  { name: "Featherweave", kind: KIND.TRINKET, slot: "chest", stack: 1, color: "#cfc7e0", effect: { move: 0.12, melee: 2 } },
  brace_leggings:{ name: "Brace leggings", kind: KIND.TRINKET, slot: "legs", stack: 1, color: "#5a5240", effect: { defense: 3 } },
  // goggles
  cracked_glasses:{ name: "Cracked glasses", kind: KIND.TRINKET, slot: "goggles", stack: 1, color: "#bfe0e6", effect: { vision: 2 } },
  fold_goggles:  { name: "Fold goggles", kind: KIND.TRINKET, slot: "goggles", stack: 1, color: "#b0e0d8", effect: { vision: 4 } },
  weakpoint_visor:{ name: "Weakpoint visor", kind: KIND.TRINKET, slot: "goggles", stack: 1, color: "#e05a5a", effect: { melee: 2 } },
  // neck
  regen_amulet:  { name: "Regen amulet", kind: KIND.TRINKET, slot: "neck", stack: 1, color: "#5ad0a0", effect: { regen: 1.5 } },
  fortune_charm: { name: "Fortune charm", kind: KIND.TRINKET, slot: "neck", stack: 1, color: "#d8c060", effect: { luck: 0.25 } },
  almond_pendant:{ name: "Almond-water heart", kind: KIND.TRINKET, slot: "neck", stack: 1, color: "#8fb6a4", effect: { maxhp: 40 } },
  // shoes
  worn_sneakers: { name: "Worn sneakers", kind: KIND.TRINKET, slot: "shoes", stack: 1, color: "#cfcfc0", effect: { move: 0.12 } },
  sprint_boots:  { name: "Sprint boots", kind: KIND.TRINKET, slot: "shoes", stack: 1, color: "#d8a040", effect: { move: 0.3 } },
  hover_boots:   { name: "Hover boots", kind: KIND.TRINKET, slot: "shoes", stack: 1, color: "#a0d8ff", effect: { move: 0.35 } },
  ghost_step:    { name: "Ghost step", kind: KIND.TRINKET, slot: "shoes", stack: 1, color: "#8a8aa0", effect: { move: 0.18, noise: -1 } },
  // gloves
  power_fist:    { name: "Power fist", kind: KIND.TRINKET, slot: "gloves", stack: 1, color: "#7a5a3a", effect: { melee: 4 } },
  powered_gauntlet:{ name: "Powered gauntlet", kind: KIND.TRINKET, slot: "gloves", stack: 1, color: "#5a6a7a", effect: { mineSpeed: 0.5 } },
  tractor_glove: { name: "Tractor glove", kind: KIND.TRINKET, slot: "gloves", stack: 1, color: "#6a7a5a", effect: { pickup: 3 } },
  // back
  backpack:      { name: "Backpack", kind: KIND.TRINKET, slot: "back", stack: 1, color: "#6a4a2a", effect: { carry: 1 } },
  wings:         { name: "Wings", kind: KIND.TRINKET, slot: "back", stack: 1, color: "#e0e0f0", effect: { move: 0.25, fly: 1 } },
  quiver:        { name: "Quiver", kind: KIND.TRINKET, slot: "back", stack: 1, color: "#8a6a3a", effect: {} },
  grenade_bandolier:{ name: "Grenade bandolier", kind: KIND.TRINKET, slot: "back", stack: 1, color: "#5a6a4a", effect: {} },
  oxygen_tank:   { name: "Oxygen tank", kind: KIND.TRINKET, slot: "back", stack: 1, color: "#7aa0c0", effect: {} },
  headlamp:      { name: "Headlamp", kind: KIND.TRINKET, slot: "goggles", stack: 1, color: "#e8e060", effect: { light: 3, vision: 1 } },
  // free / pocket devices + charms
  the_phone:     { name: "The Phone", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#202028", effect: { vision: 3, light: 1, foldradar: 1 } },
  walkman:       { name: "Walkman", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#444", effect: {} },
  lucky_penny:   { name: "Lucky penny", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#b87333", effect: { luck: 0.1 } },
  rabbits_foot:  { name: "Rabbit's foot", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#d8d0c0", effect: { luck: 0.15 } },
  anomalous_marble:{ name: "Anomalous marble", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#a45ff0", effect: { blink: 1 } },
  // ---- capstone trinkets (tinker-merge endpoints) ----
  storm_boots:   { name: "Storm boots", kind: KIND.TRINKET, slot: "shoes", stack: 1, color: "#6ad0ff", effect: { move: 0.4 } },
  blink_boots:   { name: "Blink boots", kind: KIND.TRINKET, slot: "shoes", stack: 1, color: "#b06aff", effect: { move: 0.3, blink: 1 } },
  jetpack:       { name: "Jetpack", kind: KIND.TRINKET, slot: "back", stack: 1, color: "#c0c0d0", effect: { move: 0.2, fly: 1 } },
  scanner:       { name: "Scanner", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#2a4a3a", effect: { vision: 3, foldradar: 1 } },
  war_rig:       { name: "War rig", kind: KIND.TRINKET, slot: "chest", stack: 1, color: "#5a2a2a", effect: { defense: 8, melee: 4 } },
  hazard_suit:   { name: "Hazard suit", kind: KIND.TRINKET, slot: "chest", stack: 1, color: "#c0a030", effect: { defense: 8, fireimmune: 1 } },
  survivors_rig: { name: "Survivor's rig", kind: KIND.TRINKET, slot: "chest", stack: 1, color: "#3a5a3a", effect: { defense: 10, regen: 1.5 } },
  reapers_cloak: { name: "Reaper's cloak", kind: KIND.TRINKET, slot: "back", stack: 1, color: "#2a2230", effect: { move: 0.2, noise: -2 } },
  glow_moth_charm:{ name: "Glow-moth charm", kind: KIND.TRINKET, slot: "neck", stack: 1, color: "#9ad0a0", effect: { light: 2 } },
  diving_suit:   { name: "Diving suit", kind: KIND.TRINKET, slot: "back", stack: 1, color: "#3a6a8a", effect: { defense: 4 } },
  shock_baton:   { name: "Shock baton", kind: KIND.TOOL, stack: 1 },

  // ===========================================================================
  // JUNK — mundane found objects (loot biomes). Fodder for tinker fusions (§8i)
  // and single-output salvage (§8c). kind RESOURCE so they're inert + stackable.
  // ===========================================================================
  // office
  stapler:       { name: "Stapler", kind: KIND.RESOURCE, stack: 50, color: "#566", junk: 1 },
  tape_dispenser:{ name: "Tape dispenser", kind: KIND.RESOURCE, stack: 50, color: "#777", junk: 1 },
  calculator:    { name: "Calculator", kind: KIND.RESOURCE, stack: 50, color: "#445", junk: 1 },
  typewriter:    { name: "Typewriter", kind: KIND.RESOURCE, stack: 20, color: "#3a3a3a", junk: 1 },
  rotary_phone:  { name: "Rotary phone", kind: KIND.RESOURCE, stack: 30, color: "#2a2a2a", junk: 1 },
  clipboard:     { name: "Clipboard", kind: KIND.RESOURCE, stack: 50, color: "#a98", junk: 1 },
  letter_opener: { name: "Letter opener", kind: KIND.RESOURCE, stack: 50, color: "#998", junk: 1 },
  desk_lamp:     { name: "Desk lamp", kind: KIND.RESOURCE, stack: 30, color: "#888", junk: 1 },
  paperweight:   { name: "Paperweight", kind: KIND.RESOURCE, stack: 50, color: "#9aa", junk: 1 },
  keycard:       { name: "Keycard", kind: KIND.RESOURCE, stack: 50, color: "#3a6", junk: 1 },
  ruler:         { name: "Ruler", kind: KIND.RESOURCE, stack: 50, color: "#caa", junk: 1 },
  name_badge:    { name: "Name badge", kind: KIND.RESOURCE, stack: 50, color: "#ccd", junk: 1 },
  lanyard:       { name: "Lanyard", kind: KIND.RESOURCE, stack: 50, color: "#a55", junk: 1 },
  paper:         { name: "Paper", kind: KIND.RESOURCE, stack: 200, color: "#eee", junk: 1 },
  // maintenance
  wrench:        { name: "Wrench", kind: KIND.RESOURCE, stack: 50, color: "#889", junk: 1 },
  screwdriver:   { name: "Screwdriver", kind: KIND.RESOURCE, stack: 50, color: "#a76", junk: 1 },
  pliers:        { name: "Pliers", kind: KIND.RESOURCE, stack: 50, color: "#778", junk: 1 },
  hammer:        { name: "Hammer", kind: KIND.RESOURCE, stack: 50, color: "#765", junk: 1 },
  bolt_cutters:  { name: "Bolt cutters", kind: KIND.RESOURCE, stack: 20, color: "#a44", junk: 1 },
  duct_tape:     { name: "Duct tape", kind: KIND.RESOURCE, stack: 50, color: "#999", junk: 1 },
  wd40:          { name: "WD-40", kind: KIND.RESOURCE, stack: 50, color: "#c83", junk: 1 },
  extension_cord:{ name: "Extension cord", kind: KIND.RESOURCE, stack: 50, color: "#553", junk: 1 },
  power_strip:   { name: "Power strip", kind: KIND.RESOURCE, stack: 30, color: "#eee", junk: 1 },
  surge_protector:{ name: "Surge protector", kind: KIND.RESOURCE, stack: 30, color: "#445", junk: 1 },
  multimeter:    { name: "Multimeter", kind: KIND.RESOURCE, stack: 30, color: "#c80", junk: 1 },
  circuit_tester:{ name: "Circuit tester", kind: KIND.RESOURCE, stack: 30, color: "#3a6", junk: 1 },
  light_tube:    { name: "Light tube", kind: KIND.RESOURCE, stack: 30, color: "#dfe", junk: 1 },
  fire_extinguisher:{ name: "Fire extinguisher", kind: KIND.RESOURCE, stack: 20, color: "#b33", junk: 1 },
  first_aid_kit: { name: "First-aid kit", kind: KIND.RESOURCE, stack: 20, color: "#eee", junk: 1 },
  defibrillator: { name: "Defibrillator", kind: KIND.RESOURCE, stack: 10, color: "#c91", junk: 1 },
  ladder:        { name: "Ladder", kind: KIND.RESOURCE, stack: 10, color: "#a85", junk: 1 },
  bucket:        { name: "Bucket", kind: KIND.RESOURCE, stack: 30, color: "#778", junk: 1 },
  mop:           { name: "Mop", kind: KIND.RESOURCE, stack: 20, color: "#986", junk: 1 },
  spray_bottle:  { name: "Spray bottle", kind: KIND.RESOURCE, stack: 50, color: "#7ac", junk: 1 },
  rag:           { name: "Rag", kind: KIND.RESOURCE, stack: 100, color: "#aa8", junk: 1 },
  // electronics
  radio:         { name: "Radio", kind: KIND.RESOURCE, stack: 30, color: "#544", junk: 1 },
  walkie_talkie: { name: "Walkie-talkie", kind: KIND.RESOURCE, stack: 30, color: "#343", junk: 1 },
  cassette:      { name: "Cassette tape", kind: KIND.RESOURCE, stack: 100, color: "#222", junk: 1 },
  cassette_player:{ name: "Cassette player", kind: KIND.RESOURCE, stack: 30, color: "#333", junk: 1 },
  headphones:    { name: "Headphones", kind: KIND.RESOURCE, stack: 30, color: "#222", junk: 1 },
  vhs:           { name: "VHS tape", kind: KIND.RESOURCE, stack: 100, color: "#211", junk: 1 },
  motherboard:   { name: "Motherboard", kind: KIND.RESOURCE, stack: 30, color: "#264", junk: 1 },
  hard_drive:    { name: "Hard drive", kind: KIND.RESOURCE, stack: 30, color: "#778", junk: 1 },
  server_blade:  { name: "Server blade", kind: KIND.RESOURCE, stack: 20, color: "#556", junk: 1 },
  soldering_iron:{ name: "Soldering iron", kind: KIND.RESOURCE, stack: 30, color: "#a63", junk: 1 },
  capacitor:     { name: "Capacitor", kind: KIND.RESOURCE, stack: 100, color: "#48a", junk: 1 },
  vacuum_tube:   { name: "Vacuum tube", kind: KIND.RESOURCE, stack: 50, color: "#fda", junk: 1 },
  led_strip:     { name: "LED strip", kind: KIND.RESOURCE, stack: 50, color: "#5d5", junk: 1 },
  projector:     { name: "Projector", kind: KIND.RESOURCE, stack: 10, color: "#445", junk: 1 },
  speaker:       { name: "Speaker", kind: KIND.RESOURCE, stack: 30, color: "#333", junk: 1 },
  magnet:        { name: "Magnet", kind: KIND.RESOURCE, stack: 100, color: "#a44", junk: 1 },
  // domestic (suburb)
  kitchen_knife: { name: "Kitchen knife", kind: KIND.RESOURCE, stack: 50, color: "#ccd", junk: 1 },
  frying_pan:    { name: "Frying pan", kind: KIND.RESOURCE, stack: 30, color: "#333", junk: 1 },
  pan_lid:       { name: "Pan lid", kind: KIND.RESOURCE, stack: 30, color: "#778", junk: 1 },
  toaster:       { name: "Toaster", kind: KIND.RESOURCE, stack: 20, color: "#aab", junk: 1 },
  microwave:     { name: "Microwave", kind: KIND.RESOURCE, stack: 10, color: "#889", junk: 1 },
  blender:       { name: "Blender", kind: KIND.RESOURCE, stack: 20, color: "#9ac", junk: 1 },
  kettle:        { name: "Kettle", kind: KIND.RESOURCE, stack: 20, color: "#aaa", junk: 1 },
  can_opener:    { name: "Can opener", kind: KIND.RESOURCE, stack: 50, color: "#998", junk: 1 },
  cutlery:       { name: "Cutlery", kind: KIND.RESOURCE, stack: 100, color: "#ccd", junk: 1 },
  mason_jar:     { name: "Mason jar", kind: KIND.RESOURCE, stack: 100, color: "#cee", junk: 1 },
  spice_rack:    { name: "Spice rack", kind: KIND.RESOURCE, stack: 30, color: "#a75", junk: 1 },
  cookbook:      { name: "Cookbook", kind: KIND.RESOURCE, stack: 50, color: "#964", junk: 1 },
  sewing_kit:    { name: "Sewing kit", kind: KIND.RESOURCE, stack: 30, color: "#b89", junk: 1 },
  yarn:          { name: "Yarn", kind: KIND.RESOURCE, stack: 100, color: "#c69", junk: 1 },
  quilt:         { name: "Quilt", kind: KIND.RESOURCE, stack: 30, color: "#b87", junk: 1 },
  pillow:        { name: "Pillow", kind: KIND.RESOURCE, stack: 30, color: "#dda", junk: 1 },
  alarm_clock:   { name: "Alarm clock", kind: KIND.RESOURCE, stack: 30, color: "#a44", junk: 1 },
  wind_up_clock: { name: "Wind-up clock", kind: KIND.RESOURCE, stack: 30, color: "#963", junk: 1 },
  music_box:     { name: "Music box", kind: KIND.RESOURCE, stack: 20, color: "#a86", junk: 1 },
  harmonica:     { name: "Harmonica", kind: KIND.RESOURCE, stack: 50, color: "#889", junk: 1 },
  ukulele:       { name: "Ukulele", kind: KIND.RESOURCE, stack: 20, color: "#b95", junk: 1 },
  picture_frame: { name: "Picture frame", kind: KIND.RESOURCE, stack: 50, color: "#a86", junk: 1 },
  photo:         { name: "Photograph", kind: KIND.RESOURCE, stack: 100, color: "#cba", junk: 1 },
  vase:          { name: "Vase", kind: KIND.RESOURCE, stack: 30, color: "#9bb", junk: 1 },
  candlestick:   { name: "Candlestick", kind: KIND.RESOURCE, stack: 50, color: "#cb6", junk: 1 },
  matchbook:     { name: "Matchbook", kind: KIND.RESOURCE, stack: 100, color: "#a55", junk: 1 },
  lighter:       { name: "Lighter", kind: KIND.RESOURCE, stack: 100, color: "#c84", junk: 1 },
  board_game:    { name: "Board game", kind: KIND.RESOURCE, stack: 20, color: "#a76", junk: 1 },
  deck_of_cards: { name: "Deck of cards", kind: KIND.RESOURCE, stack: 100, color: "#ccd", junk: 1 },
  dice:          { name: "Dice", kind: KIND.RESOURCE, stack: 100, color: "#eee", junk: 1 },
  marbles:       { name: "Marbles", kind: KIND.RESOURCE, stack: 100, color: "#8bd", junk: 1 },
  yo_yo:         { name: "Yo-yo", kind: KIND.RESOURCE, stack: 50, color: "#d55", junk: 1 },
  christmas_lights:{ name: "Christmas lights", kind: KIND.RESOURCE, stack: 50, color: "#6c6", junk: 1 },
  ornament:      { name: "Ornament", kind: KIND.RESOURCE, stack: 100, color: "#d66", junk: 1 },
  tinsel:        { name: "Tinsel", kind: KIND.RESOURCE, stack: 100, color: "#dd6", junk: 1 },
  snow_globe:    { name: "Snow globe", kind: KIND.RESOURCE, stack: 30, color: "#bce", junk: 1 },
  broom_handle:  { name: "Broom handle", kind: KIND.RESOURCE, stack: 50, color: "#a85", junk: 1 },
  nails:         { name: "Nails", kind: KIND.RESOURCE, stack: 200, color: "#998", junk: 1 },
  jumper_cables: { name: "Jumper cables", kind: KIND.RESOURCE, stack: 30, color: "#b33", junk: 1 },
  beans:         { name: "Coffee beans", kind: KIND.RESOURCE, stack: 100, color: "#642", junk: 1 },
  // pool / wet
  swim_cap:      { name: "Swim cap", kind: KIND.RESOURCE, stack: 50, color: "#3aa", junk: 1 },
  kickboard:     { name: "Kickboard", kind: KIND.RESOURCE, stack: 30, color: "#5ad", junk: 1 },
  pool_noodle:   { name: "Pool noodle", kind: KIND.RESOURCE, stack: 30, color: "#5c5", junk: 1 },
  towel:         { name: "Towel", kind: KIND.RESOURCE, stack: 50, color: "#dca", junk: 1 },
  flip_flops:    { name: "Flip-flops", kind: KIND.RESOURCE, stack: 50, color: "#3a8", junk: 1 },
  diving_mask:   { name: "Diving mask", kind: KIND.RESOURCE, stack: 30, color: "#359", junk: 1 },
  snorkel:       { name: "Snorkel", kind: KIND.RESOURCE, stack: 30, color: "#5ac", junk: 1 },
  flippers:      { name: "Flippers", kind: KIND.RESOURCE, stack: 30, color: "#37a", junk: 1 },
  inflatable:    { name: "Inflatable", kind: KIND.RESOURCE, stack: 20, color: "#dc5", junk: 1 },
  beach_ball:    { name: "Beach ball", kind: KIND.RESOURCE, stack: 20, color: "#e66", junk: 1 },
  lifebuoy:      { name: "Lifebuoy", kind: KIND.RESOURCE, stack: 20, color: "#f73", junk: 1 },
  canteen:       { name: "Canteen", kind: KIND.RESOURCE, stack: 50, color: "#797", junk: 1 },
  chlorine:      { name: "Chlorine tablets", kind: KIND.RESOURCE, stack: 100, color: "#cec", junk: 1 },
  // anomalous found objects
  skeleton_key:  { name: "Skeleton key", kind: KIND.RESOURCE, stack: 20, color: "#caa", junk: 1 },
  tuning_fork:   { name: "Tuning fork", kind: KIND.RESOURCE, stack: 30, color: "#bcd", junk: 1 },
  jar_of_teeth:  { name: "Jar of teeth", kind: KIND.RESOURCE, stack: 30, color: "#dcb", junk: 1 },
  single_shoe:   { name: "A single shoe", kind: KIND.RESOURCE, stack: 50, color: "#987", junk: 1 },
  fold_compass:  { name: "Fold compass", kind: KIND.RESOURCE, stack: 20, color: "#9ed", junk: 1 },

  // ===========================================================================
  // TREASURE — trinket seeds (weak; grow via the tinker tree §8f) + the tree's
  // intermediate and capstone trinkets. slot + effect (effects stack; §8e).
  // ===========================================================================
  // mobility seeds
  heely:         { name: "Heely", kind: KIND.TRINKET, slot: "shoes", stack: 1, color: "#c66", effect: { move: 0.06 } },
  spring_shoe:   { name: "Spring shoe", kind: KIND.TRINKET, slot: "shoes", stack: 1, color: "#7a7", effect: { move: 0.05 } },
  red_balloon:   { name: "Red balloon", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#d44", effect: { move: 0.04 } },
  helium_pocket: { name: "Helium pocket", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#dd8", effect: { move: 0.05 } },
  galoshes:      { name: "Galoshes", kind: KIND.TRINKET, slot: "shoes", stack: 1, color: "#5a6", effect: { move: 0.05, defense: 1 } },
  // explorer/sensory seeds
  office_compass:{ name: "Office compass", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#aa6", effect: { vision: 1 } },
  magnifier:     { name: "Magnifier", kind: KIND.TRINKET, slot: "goggles", stack: 1, color: "#ace", effect: { vision: 1 } },
  dowsing_twig:  { name: "Dowsing twig", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#8a5", effect: { mineSpeed: 0.1 } },
  disposable_camera:{ name: "Disposable camera", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#779", effect: { vision: 1 } },
  pedometer:     { name: "Pedometer", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#9a9", effect: { vision: 1 } },
  penlight:      { name: "Penlight", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#dd9", effect: { light: 1 } },
  // combat seeds
  brass_knuckle: { name: "Brass knuckle", kind: KIND.TRINKET, slot: "gloves", stack: 1, color: "#b94", effect: { melee: 1 } },
  pocketknife:   { name: "Pocketknife", kind: KIND.TRINKET, slot: "gloves", stack: 1, color: "#aab", effect: { melee: 1 } },
  static_glove:  { name: "Static glove", kind: KIND.TRINKET, slot: "gloves", stack: 1, color: "#9ad", effect: { melee: 1 } },
  adrenaline_vial:{ name: "Adrenaline vial", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#d77", effect: { melee: 1 } },
  nail_bracelet: { name: "Nail bracelet", kind: KIND.TRINKET, slot: "neck", stack: 1, color: "#998", effect: { melee: 1 } },
  // survival seeds
  pill_bottle:   { name: "Pill bottle", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#dba", effect: { regen: 0.5 } },
  oven_mitt:     { name: "Oven mitt", kind: KIND.TRINKET, slot: "gloves", stack: 1, color: "#c85", effect: { defense: 1 } },
  dust_mask:     { name: "Dust mask", kind: KIND.TRINKET, slot: "head", stack: 1, color: "#ccd", effect: { defense: 1 } },
  wool_sock:     { name: "Wool sock", kind: KIND.TRINKET, slot: "shoes", stack: 1, color: "#ca8", effect: { defense: 1 } },
  canteen_sip:   { name: "Canteen sip", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#7a7", effect: { regen: 0.4 } },
  knee_brace:    { name: "Knee brace", kind: KIND.TRINKET, slot: "legs", stack: 1, color: "#998", effect: { defense: 1 } },
  // stealth/anomalous seeds
  felt_slipper:  { name: "Felt slipper", kind: KIND.TRINKET, slot: "shoes", stack: 1, color: "#a99", effect: { noise: -1 } },
  moth_jar:      { name: "Moth in a jar", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#cd9", effect: { light: 1 } },
  chipped_marble:{ name: "Chipped marble", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#9bd", effect: { blink: 1 } },
  pocket_mirror: { name: "Pocket mirror", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#bcd", effect: { vision: 1 } },
  sand_timer:    { name: "Sand timer", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#dc9", effect: { move: 0.05 } },
  rosary:        { name: "Rosary", kind: KIND.TRINKET, slot: "neck", stack: 1, color: "#bba", effect: { defense: 1 } },
  // utility seeds
  keyring:       { name: "Keyring", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#cb6", effect: { luck: 0.05 } },
  multitool:     { name: "Multitool", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#a99", effect: { mineSpeed: 0.1 } },
  zippo:         { name: "Zippo", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#cb5", effect: { light: 2 } },
  magnet_bit:    { name: "Magnet bit", kind: KIND.TRINKET, slot: "gloves", stack: 1, color: "#a55", effect: { pickup: 1 } },
  everlasting_battery:{ name: "Everlasting battery", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#5c8", effect: { light: 1 } },

  // tinker-tree intermediates (refine >> / merge +)
  runners_boot:  { name: "Runner's boot", kind: KIND.TRINKET, slot: "shoes", stack: 1, color: "#d93", effect: { move: 0.22 } },
  track_spike:   { name: "Track spike", kind: KIND.TRINKET, slot: "shoes", stack: 1, color: "#e84", effect: { move: 0.28 } },
  dash_boot:     { name: "Dash boot", kind: KIND.TRINKET, slot: "shoes", stack: 1, color: "#db5", effect: { move: 0.2 } },
  cloud_jar:     { name: "Cloud jar", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#cdf", effect: { move: 0.08 } },
  cumulus:       { name: "Cumulus charm", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#def", effect: { move: 0.1, fly: 1 } },
  brass_compass: { name: "Brass compass", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#b94", effect: { foldradar: 1 } },
  reading_glasses:{ name: "Reading glasses", kind: KIND.TRINKET, slot: "goggles", stack: 1, color: "#cde", effect: { vision: 2 } },
  loupe:         { name: "Jeweler's loupe", kind: KIND.TRINKET, slot: "goggles", stack: 1, color: "#bdf", effect: { vision: 3, melee: 1 } },
  surveyor_rod:  { name: "Surveyor's rod", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#8b6", effect: { mineSpeed: 0.2 } },
  fold_monocle:  { name: "Fold monocle", kind: KIND.TRINKET, slot: "goggles", stack: 1, color: "#9ec", effect: { vision: 3, foldradar: 1 } },
  fold_lens:     { name: "Fold lens", kind: KIND.TRINKET, slot: "goggles", stack: 1, color: "#aed", effect: { vision: 4, foldradar: 1 } },
  instant_camera:{ name: "Instant camera", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#88a", effect: { vision: 2 } },
  detector:      { name: "Detector", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#3a5", effect: { vision: 1, foldradar: 1 } },
  navigator:     { name: "Navigator", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#5ad", effect: { vision: 2, foldradar: 1 } },
  recorder:      { name: "Recorder", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#48b", effect: { vision: 3, foldradar: 1 } },
  spiked_knuckle:{ name: "Spiked knuckle", kind: KIND.TRINKET, slot: "gloves", stack: 1, color: "#c85", effect: { melee: 2 } },
  knuckle_duster:{ name: "Knuckle duster", kind: KIND.TRINKET, slot: "gloves", stack: 1, color: "#da6", effect: { melee: 3 } },
  tesla_glove:   { name: "Tesla glove", kind: KIND.TRINKET, slot: "gloves", stack: 1, color: "#7bf", effect: { melee: 2 } },
  combat_stim:   { name: "Combat stim", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#e66", effect: { melee: 2 } },
  berserker_core:{ name: "Berserker core", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#b33", effect: { melee: 3, defense: -1 } },
  shock_aura:    { name: "Shock aura", kind: KIND.TRINKET, slot: "neck", stack: 1, color: "#7cf", effect: { melee: 2 } },
  first_aid_core:{ name: "First-aid core", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#ded", effect: { regen: 1 } },
  fireman_coat:  { name: "Fireman's coat", kind: KIND.TRINKET, slot: "chest", stack: 1, color: "#b54", effect: { defense: 3, fireimmune: 1 } },
  hazmat_coat:   { name: "Hazmat coat", kind: KIND.TRINKET, slot: "chest", stack: 1, color: "#cb3", effect: { defense: 5, fireimmune: 1 } },
  brimming_heart:{ name: "Brimming heart", kind: KIND.TRINKET, slot: "neck", stack: 1, color: "#7d9", effect: { maxhp: 60 } },
  regen_core:    { name: "Regen core", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#6d9", effect: { regen: 2 } },
  ghost_sole:    { name: "Ghost sole", kind: KIND.TRINKET, slot: "shoes", stack: 1, color: "#99a", effect: { move: 0.1, noise: -2 } },
  moth_shroud:   { name: "Moth shroud", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#cb9", effect: { noise: -1, light: 1 } },
  warp_marble:   { name: "Warp marble", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#b7e", effect: { blink: 1, move: 0.05 } },
  chrono_charm:  { name: "Chrono charm", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#dca", effect: { move: 0.1 } },
  recall_stone:  { name: "Recall stone", kind: KIND.TRINKET, slot: "neck", stack: 1, color: "#9cd", effect: { vision: 1, foldradar: 1 } },
  phase_charm:   { name: "Phase charm", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#c8e", effect: { blink: 1, defense: 2 } },
  master_key:    { name: "Master key", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#db7", effect: { luck: 0.1 } },
  good_fortune:  { name: "Good fortune", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#dc6", effect: { luck: 0.15 } },
  jackpot_charm: { name: "Jackpot charm", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#ec5", effect: { luck: 0.3 } },
  bone_charm:    { name: "Bone charm", kind: KIND.TRINKET, slot: "neck", stack: 1, color: "#dcb", effect: { defense: 2 } },
  // more capstones by slot (§8g/8h)
  logistics_lens:{ name: "Logistics lens", kind: KIND.TRINKET, slot: "goggles", stack: 1, color: "#6cb", effect: { vision: 2 } },
  blueprint_goggles:{ name: "Blueprint goggles", kind: KIND.TRINKET, slot: "goggles", stack: 1, color: "#69d", effect: { vision: 2, mineSpeed: 0.2 } },
  nightsight_goggles:{ name: "Nightsight goggles", kind: KIND.TRINKET, slot: "goggles", stack: 1, color: "#6d6", effect: { vision: 3, light: 1 } },
  bottomless_toolbag:{ name: "Bottomless toolbag", kind: KIND.TRINKET, slot: "back", stack: 1, color: "#86a", effect: { carry: 2 } },
  capacitor_vest:{ name: "Capacitor vest", kind: KIND.TRINKET, slot: "chest", stack: 1, color: "#48a", effect: { defense: 4 } },
  bulwark_plate: { name: "Bulwark plate", kind: KIND.TRINKET, slot: "chest", stack: 1, color: "#667", effect: { defense: 14, move: -0.15 } },
  shield_gauntlet:{ name: "Shield gauntlet", kind: KIND.TRINKET, slot: "gloves", stack: 1, color: "#778", effect: { defense: 4 } },
  ablative_pack: { name: "Ablative pack", kind: KIND.TRINKET, slot: "back", stack: 1, color: "#587", effect: { defense: 3, maxhp: 20 } },
  taunt_amulet:  { name: "Taunt amulet", kind: KIND.TRINKET, slot: "neck", stack: 1, color: "#c66", effect: { defense: 2 } },
  bloodlust_amulet:{ name: "Bloodlust amulet", kind: KIND.TRINKET, slot: "neck", stack: 1, color: "#a22", effect: { melee: 5, defense: -3 } },
  momentum_pendant:{ name: "Momentum pendant", kind: KIND.TRINKET, slot: "neck", stack: 1, color: "#8ac", effect: { move: 0.12 } },
  the_towel:     { name: "The towel", kind: KIND.TRINKET, slot: "free", stack: 1, color: "#dca", effect: { defense: 1, regen: 0.3 } },
  life_ring:     { name: "Life ring", kind: KIND.TRINKET, slot: "neck", stack: 1, color: "#f73", effect: { defense: 1 } },
  swim_fins:     { name: "Swim fins", kind: KIND.TRINKET, slot: "shoes", stack: 1, color: "#37a", effect: { move: 0.1 } },
  lanyard_id:    { name: "Lanyard ID", kind: KIND.TRINKET, slot: "neck", stack: 1, color: "#9a9", effect: { noise: -1 } },

  // ---- junk-fusion results: improvised weapons / devices / lights (§8i) ----
  skillet_bat:   { name: "Skillet bat", kind: KIND.TOOL, stack: 1 },
  shiv:          { name: "Shiv", kind: KIND.TOOL, stack: 1 },
  knife_fan:     { name: "Knife fan", kind: KIND.TOOL, stack: 1 },
  co2_blaster:   { name: "CO₂ blaster", kind: KIND.TOOL, stack: 1 },
  flame_sprayer: { name: "Flame sprayer", kind: KIND.TOOL, stack: 1 },
  shock_whip:    { name: "Shock whip", kind: KIND.TOOL, stack: 1 },
  glaive:        { name: "Glaive", kind: KIND.TOOL, stack: 1 },
  paperclip_crossbow:{ name: "Paperclip crossbow", kind: KIND.TOOL, stack: 1, ranged: true, bow: true },
  glow_jar:      { name: "Glow jar", kind: KIND.BUILDABLE, stack: 50, w: 1, h: 1, color: "#7ad0a0", light: 4 },
  moth_lantern:  { name: "Moth lantern", kind: KIND.BUILDABLE, stack: 30, w: 1, h: 1, color: "#cd9", light: 5 },
  portable_lamp: { name: "Portable lamp", kind: KIND.BUILDABLE, stack: 30, w: 1, h: 1, color: "#dd9", light: 5 },
  candle:        { name: "Candle", kind: KIND.BUILDABLE, stack: 50, w: 1, h: 1, color: "#cb6", light: 3 },
  firecracker:   { name: "Firecracker", kind: KIND.INTERMEDIATE, stack: 50, color: "#d55" },
  coffee:        { name: "Coffee", kind: KIND.RESOURCE, stack: 50, color: "#642" },
  bandages:      { name: "Bandages", kind: KIND.RESOURCE, stack: 50, color: "#eed" },
};

export const itemName = (id) => (ITEMS[id] ? ITEMS[id].name : id);
export const itemKind = (id) => (ITEMS[id] ? ITEMS[id].kind : null);
export const isBuildable = (id) => itemKind(id) === KIND.BUILDABLE;
export const isTool = (id) => itemKind(id) === KIND.TOOL;
export const isTrinket = (id) => itemKind(id) === KIND.TRINKET;
export const trinketSlot = (id) => (ITEMS[id] ? ITEMS[id].slot : null);
export const itemEffect = (id) => (ITEMS[id] && ITEMS[id].effect) || {};
export const isModule = (id) => !!(ITEMS[id] && ITEMS[id].module);
export const moduleStats = (id) => (ITEMS[id] && ITEMS[id].module) || {};
